services:
  api:
    # Hot reload for development
    command: /bin/sh -lc "[ -d /app/.venv ] || python -m venv /app/.venv; if [ -f /app/.venv/bin/activate ]; then . /app/.venv/bin/activate; fi; if [ -n \"${USER_ID}\" ] && [ -n \"${GROUP_ID}\" ]; then chown -R ${USER_ID}:${GROUP_ID} /app/.venv || true; fi; python -m pip install -U pip setuptools wheel || true; if [ -n \"${TORCH_INDEX_URL}\" ]; then pip install --index-url \"${TORCH_INDEX_URL}\" torch || true; fi; pip install -e .; uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      - LOG_LEVEL=DEBUG
      # Optional: set these before make dev-up to ensure .venv ownership matches host
      - USER_ID
      - GROUP_ID
      # If you need torch in dev, keep CPU index; remove if not needed
      - TORCH_INDEX_URL=https://download.pytorch.org/whl/cpu
    volumes:
      - ./:/app
      # removed container venv volume; using project-local .venv
      # - venv_cache:/opt/venv
      - pip_cache:/root/.cache/pip
    # Ensure file change notifications work on some hosts
    # (optional) increase inotify watches for heavy reloads
    # sysctls:
    #   - fs.inotify.max_user_watches=524288
