version: '3.8'
services:
  api:
    build:
      context: ..
      dockerfile: infra/Dockerfile
      args:
        TORCH_VARIANT: ${TORCH_VARIANT:-cpu}
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    environment:
      # Optional: protect /metrics with a token. If unset or empty, /metrics is open.
      - METRICS_TOKEN=${METRICS_TOKEN:-}
    volumes:
      - ../app:/app/app:rw
      - ../.env:/app/.env:ro
