version: '3.8'
services:
  api:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    volumes:
      - ../app:/app/app:rw
      - ../.env:/app/.env:ro
