name: openapi-drift-check
on:
  pull_request:
    branches: [ "**" ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install project
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -e .
          pip install pyyaml
      - name: Regenerate OpenAPI
        run: |
          . .venv/bin/activate
          python scripts/export_openapi.py
      - name: Check drift
        run: |
          git diff --exit-code docs/openapi.yaml || {
            echo "::error::OpenAPI schema drift detected. Run: . .venv/bin/activate && python scripts/export_openapi.py and commit changes.";
            exit 1;
          }
